---
- name: kafka_exporter 源文件分发
  copy: src=/etc/ansible/roles/kafka_install/file/kafka_exporter-1.2.0.linux-amd64.tar.gz dest=/root/exporter/kafka_exporter-1.2.0.linux-amd64.tar.gz

- name: kafka_exporter 安装
  shell: tar zxf /root/exporter/kafka_exporter-1.2.0.linux-amd64.tar.gz -C /root/exporter && cp /root/exporter/kafka_exporter-1.2.0.linux-amd64/kafka_exporter /usr/local/bin/ && useradd -rs /bin/false kafkausr

- name: kafka_exporter 启动文件分发
  template: src=/etc/ansible/roles/kafka_install/template/kafka_exporter.service.j2 dest=/etc/systemd/system/kafka_exporter.service

- name: kafka_exporter 启动
  service: name=kafka_exporter state=started enabled=yes daemon_reload=yes
