--- 
- name: logstash 源文件分发
  copy: src=/etc/ansible/roles/logstash_install/file/logstash-7.2.0.rpm dest=/root/exporter/logstash-7.2.0.rpm

- name: logstash 安装
  shell: yum -y install /root/exporter/logstash-7.2.0.rpm

- name: logstash conf 配置文件分发
  template: src=/etc/ansible/roles/logstash_install/template/logstash.conf.j2 dest=/etc/logstash/conf.d/logstash.conf

- name: logstash jvm 配置文件分发
  copy: src=/etc/ansible/roles/logstash_install/file/jvm.options dest=/etc/logstash/jvm.options

- name: logstash yml 配置文件
  copy: src=/etc/ansible/roles/logstash_install/file/logstash.yml dest=/etc/logstash/logstash.yml

- name: logstash 启动
  service: name=logstash state=started enabled=yes daemon_reload=yes
